[tool.poetry]
name = "ml-repo"
version = "0.1.0"
description = "A project for holding ML example code and utilities"
authors = ["robin.lord"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
